### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by arokem** [swcarpentry/certification#13]
How do I use these certificates? Who is allowed to provide what certification?

**Comment by arokem** [comment]
Should probably also be recorded/linked somewhere in the operations guide.

**Comment by gvwilson** [comment]
Certificates are generated upon completion of DC/SWC instructor checkout 
using bin/certificates.py; we have a PR to generate certificates 
directly from AMY, but it needs an overhaul before we integrate.  For 
now, @gvwilson generates certificates upon being pinged by instructors 
that someone has completed checkout.
Thanks,
Greg

**Comment by arokem** [comment]
how/who generates certificates for participants?

**Comment by gvwilson** [comment]
We usually don't generate certificates for participants, but we can using the same script in the same repo.
