### ISSUE TITLE
Instructions for running bin/certificates.py

### ISSUE THREAD

**Issue by drchriscole** [swcarpentry/certification#18]
Really not getting how the CSV file should be formatted and what fields like 'new_instructor' means for completion certificates. 

Help and errors are terse to the level inutility. Even the example in the code doesn't work...

More help please?

**Comment by jangari** [comment]
I second this. Some attendees of a recent workshop have requested attendance certificates. So as not to massively expand the size of this repository with blobs, perhaps the code for generating certificates should ship with the software carpentry workshop github pages repo, and it can pull metadata from the yaml, such as instructor, date, syllabus, etc.

**Comment by jduckles** [comment]
Please look at the second and pure python method for building certificates at the bottom of the readme, it is quite simple and has a functioning example. The `certificates.py` workflow is very old and outdated, assumes a particularly formatted CSV file and has fragile dependencies (Cairo) and as you've pointed out a very poor user interface.

We'd like the certificates to be officially generated by The Carpentries, and are working on integrations to make this happen in our AMY tool. The blobs in this repo, as reprehensible as they may be, act as an authoritative source to point to for those who are officially certified as instructors.
