### ISSUE TITLE
completely non-urgent: missing certificate

### ISSUE THREAD

**Issue by PBarmby** [swcarpentry/certification#2]
I *thought* I was certified, but maybe not? As I say, not urgent; I'm going to keep pretending anyway. :)

**Comment by gvwilson** [comment]
Yup, you're certified - I just haven't issued PDFs for all the digital 
badges.  On it...
G

On 2015-05-07 12:23 PM, Pauline Barmby wrote:
>
> I /thought/ I was certified, but maybe not? As I say, not urgent; I'm 
> going to keep pretending anyway. :)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/swcarpentry/certification/issues/2>.
>

-- 
Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org
