### ISSUE TITLE
Attendance vs achievement vs completion

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/certification#5]
We have https://github.com/swcarpentry/certification/blob/master/attendance.svg and https://github.com/swcarpentry/certification/blob/master/completion.svg that are almost the same.

@gvwilson could you remove the duplicate and improve if need the other?

**Comment by gvwilson** [comment]
As soon as we figure out what we actually want to do...

**Comment by gvwilson** [comment]
We need a discussion of what certificates we ought to be handing out.

**Comment by anelda** [comment]
Hi all, how is this discussion progressing? We had enquiries about certificates of attendance in our last workshop again? Do we have a template for that? I would be hesitant to issue "Certificate of Achievement" as it may create the idea that we've evaluated the ability of participants to do what the certificate states? Thanks!

**Comment by tracykteal** [comment]
We do have certificate of attendance certificate templates. We give them to participants when they request them. Some people like or need to have them as evidence of continuing education. We should still continue to have this discussion, but if you'd like some certificates now, send me an email and we can get you the certificates.
